# Generated by Django 5.1.3 on 2024-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_user_managers_remove_card_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cvv',
        ),
        migrations.AddField(
            model_name='card',
            name='_card_number',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='_cvv',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
